### ISSUE TITLE
Se cierra nada más abrir y poner la introducción en Windows Glulxe

### ISSUE THREAD

**Issue by sukiletxe** [ricpelo/alien#2]
No puedo usar Gargoile porque no es accesible con lectores de pantalla. Incluso si activo la opción texto a voz en `garglk.ini`, no me lee los ítems de los menús.

Creo recordar que antes el juego iba con glulxe, ¿hay algún motivo por el que esto se haya cambiado? ¿Se podrían habilitar alternativas para que tirara por ambos sitios?

Como alternativa, sé que en Windows Glulxe están habilitando extensiones de glk, ¿hay alguna cosa a tener en cuenta para transmitirles a los desarrolladores para que lo incorporen para que funcione en este caso?

**Comment by ricpelo** [comment]
Hola, @sukiletxe . Es la primera noticia que tengo respecto a que Gargoyle no es compatible con lectores de pantalla. Sé que otros usuarios, colaboradores activos del foro del CAAD, han usado lectores de pantalla para jugar a A·L·I·E·N sin ningún problema especial. En todo caso, siempre puedes usar otro intérprete, ya que no es estrictamente necesario que uses Gargoyle (a fin de cuentas, éste no es más que un *front-end* para otros intérpretes como Glulxe o Git).

Con respecto a los menús, puedes desactivar el efecto de dibujado letra a letra (teletipo) en las opciones de accesibilidad.

Espero que te sirva de ayuda. Un saludo.

**Comment by sukiletxe** [comment]
Hola:
He hojeado [un tema del foro del CAAD](https://foro.caad.es/viewtopic.php?f=9&t=5139) donde se habla de la aventura, y creo que Gregoire utiliza Windows Glulxe. Es extraño, porque a mí con Windows Glulxe y Git se me cierra nada más abrir la aventura y mostrar el diálogo con la información bibliográfica. Como tiene pinta de ser algún error de windows GLK (más aún en versiones recientes), [se lo reporto](https://github.com/DavidKinder/Windows-Glk/issues/10). Es curioso porque la edición antigua sí me funciona correctamente.

**Comment by sukiletxe** [comment]
Se ve que lo han arreglado:

> The problem is that the game is calling glk_request_timer_events(0) before any window has opened. This shouldn't do anything, but because no windows are open, it leads to an internal error in Windows Glk. I have committed a fix for this which will be in the next release. The workaround in the meantime would be to not call glk_request_timer_events(0) during start-up before any windows open - all the call would do is stop any timers which aren't running anyway during initialization.

(Sacado de la respuesta del reporte enlazado arriba)

No lo he probado todavía porque no lo han liberado. Cierro, y si vuelve a haber problemas lo reabro. ¡Gracias!
